name: www.veda-retreats.com
on:
  push:
    branches: [ master ]

jobs:
  job_one:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
    - name: pushing latest change on www.veda-retreats.com
      uses: appleboy/ssh-action@master
      with:
        host: www.veda-retreats.com
        username: webuser
        key: ${{ secrets.TF_SECRET }}
        port: 34022
        script: |
          cd websites/www_veda-retreats/
          git log -1
          git restore .
          git pull
